# Name of workflow
name: Node CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [14.x]

    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
      - uses: actions/checkout@v2
        # Step's name
      - name: Use Node.js ${{ matrix.node-version }}
        # Configures the node version used on GitHub-hosted runners
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v1
        # The Node.js version to configure
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        # Install and build project
        run: |
          make install
        # Add environment variables
        env:
          CI: true
      - name: Run linter
        # Run Linter
        run: |
          make lint
       uses: paambaati/codeclimate-action@v2.6.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.fb4d647bc49d60c0ef82539f2945b58c4df4a87973622bc0df03cf36f250c428 }}
        with:
          coverageCommand: make test-coverage
          debug: true
